### ISSUE TITLE
Generate recomendations

### ISSUE THREAD

**Issue by satsaras** [0215Arthur/HG-GNN#10]
How we can use the saved model to generate recommendations based on on-going session activity?

**Comment by 0215Arthur** [comment]
Please refer to the process of model evaluation ([main.py#evaluation_topk](https://github.com/0215Arthur/HG-GNN/blob/d1805b7bfee7453ded305cead477eae8bc0ab97a/main.py#L152)). It can be divided into the following steps:
1. Load the saved model file.
2. Data processing, constructing session feature and item candidate set.
3. Feed feature (session & items) into the model and get the prediction scores of the model for the candidate items.
4. Based on the item scores and other actual requirements, set the recommendation rules to select items from the candidate  set and recommend them to users.
