### ISSUE TITLE
What code should I use to get the '/train_seq.pkl' data?

### ISSUE THREAD

**Issue by hyeminy** [0215Arthur/HG-GNN#2]
By using code(https://github.com/twchen/lessr/blob/master/utils/data/preprocess.py) 
I make *.txt data of lastfm

What code should I use to get the '/train_seq.pkl' data?

**Comment by lgq111** [comment]
Could you tell me how to get the '/train.pkl' data? Thank you!

**Comment by arnold-em** [comment]
how to get it did you solve it ?
tks!

**Comment by 0215Arthur** [comment]
I have uploaded the processing code `data_helper.py` which can be used to generate the train.pkl / test.pkl data. You can follow the code to process more datasets.
